name: Mekuru Meguru Auto Processor
on:
  push:
    paths:
      - 'uploads/**' # uploadsフォルダにファイルが入ったら起動

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install Pillow

      - name: Process Files
        run: |
          # ここに画像をWebPに変換したり仕分けたりする命令を書きます
          python .github/scripts/processor.py
