name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main # ボスがメインブランチにpushした時に発動します

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install # プロジェクトに合わせて yarn install 等に変更してください

      - name: Build
        run: npm run build # ビルドコマンドを実行します

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MEKURU_MEGURU }}'
          channelId: live
          projectId: mekurumeguru-beppu # 実際のプロジェクトIDに書き換えてください
